#cache:
#  directories:
#  - $HOME/.gradle/wrapper
language: groovy
addons:
  chrome: stable
  firefox: latest
env:
  global:
  - TERM=dumb
  - GRADLE_OPTS="-Xmx768m -Xms256m -XX:MaxPermSize=372m -XX:+CMSClassUnloadingEnabled"
jdk:
- oraclejdk8
- openjdk11
#- openjdk7
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
install: true # skips installation phase. otherwise ./gradlew assemble
script: ./gradlew check assemble -Dgrails.env=test -Dgeb.env=chromeHeadless
after_failure: ./travis/junit-errors-to-stdout.sh
notifications:
  slack:
    secure: Tgn1sBoxbz8qgqirJYufou/jJxQfQG4bIgnZn8f7uavwJJC7P2svM07GcTe730HTXjB7i94S7dcC0lFqSFzUx0LLEivUAJI3H7TmPQPk8FRUpC2yS7RAxnodHlleB/yKo4RPvEJYLeCwNSwbk62JPT9oq05Xct10+EOTlXql+Q4=
